### PR TITLE
switch to new mapbox acct

### LINKED ISSUE #48: Consolidate & Migrate Mapbox stylings
Migrate Mapbox data & stylings to new Herop Lab account for long-term storage/use.

### PR DESCRIPTION
**Pull request by mukeshchugani10**
Fixes #48 . Changed the json files to point to the new mapbox account. @Makosak @mradamcox To check if the new maps look similar.

### CODE REVIEW

**Comment by Makosak** [comment]
These all look generally good, except we are indeed using a different Native American reservation boundary as those areas are different from what was in the original file. Are we sure there's no hints as to which file was used by the previous developers? I had extracted a file from the Census, but that may not be the best one, and we may need to investigate further...

@mradamcox what are your thoughts -- should we push as is, or get this corrected first?

**Comment by mradamcox** [comment]
@Makosak Looking into it, I think I've found a better source for this layer, will get it to @mukeshchugani10 , as well as the segregated cities labels (will remake those).

**Comment by mukeshchugani10** [comment]
@Makosak The BIA LAR files provided by @mradamcox have been added. The segregated cities labels mentioned in #60 has been added as well.

**Review by mradamcox — APPROVED** [review]
Looks like all the new land boundaries and labels files are working properly. I think we are ready to merge this.

**Pull request merged**
